### ISSUE TITLE
missing database script?

### ISSUE THREAD

**Issue by alanhumphrey** [OpenTreeMap/otm-legacy#1]
a script to create necessary database tables appears to be missing.   Choices.sql creates and populates treemap_choices.  The FirstInstallation wiki page mentions treemap_zipcode and treemap_neighborhood as additional tables that need updating.  Running the app also gets an error complaining about treemap_tree_audit:

Exception Type:     DatabaseError
Exception Value:    

relation "treemap_tree_audit" does not exist
LINE 1: ...udit_change_type", "treemap_tree_audit"."id" FROM "treemap_t...

Is there a database script missing?

**Comment by ahinz** [comment]
Did you try running:
```python manage.py syncdb

```
This should install the audit tables for you. If you're still having issues let us know. The maintainer for the project isn't in today but can probably fix it some time tomorrow.
```

**Comment by alanhumphrey** [comment]
Yep.  That results in a "No fixtures found" message.

**Comment by alsaihn** [comment]
The Choices.sql file is the only database script for the project, everything else should be created automatically by django's syncdb command. I wasn't able to duplicate your problem. Here's what I did: I created an empty database from a postgis template, ran the Choices.sql file, made sure the db tables were all owned by the database owner, made sure the database info in the settings file was right and ran the syncdb command and everything seemed to install fine. Is it possible that a module or patch from the installation doc didn't get installed? The audit system has a direct tie-in to the reputation system, is that module configured and patched correctly?

**Comment by alanhumphrey** [comment]
Thanks for the pointer to reputation.  Turns out that I didn't copy the django_reputation directory correctly (I  installed it as django-reputation).

So with that problem fixed things go much better.  Many more tables created.  Now the error is:

Problem installing fixture '/home/alanh/src/opentreemap/azavea-OpenTreeMap-6205276/treemap/fixtures/initial_data.json': Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/django/core/management/commands/loaddata.py", line 174, in handle
    obj.save(using=using)
  File "/usr/lib/pymodules/python2.7/django/core/serializers/base.py", line 165, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/usr/lib/pymodules/python2.7/django/db/models/base.py", line 551, in save_base
    result = manager._insert(values, return_id=update_pk, using=using)
  File "/usr/lib/pymodules/python2.7/django/db/models/manager.py", line 195, in _insert
    return insert_query(self.model, values, **kwargs)
  File "/usr/lib/pymodules/python2.7/django/db/models/query.py", line 1524, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/pymodules/python2.7/django/db/models/sql/compiler.py", line 788, in execute_sql
    cursor = super(SQLInsertCompiler, self).execute_sql(None)
  File "/usr/lib/pymodules/python2.7/django/db/models/sql/compiler.py", line 732, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/pymodules/python2.7/django/db/backends/util.py", line 15, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/pymodules/python2.7/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
    return self.cursor.execute(query, args)
IntegrityError: duplicate key value violates unique constraint "treemap_species_resource_species_id_key"

Should that column even have a unique index on it?

Thanks for all your help.

-Alan

-----Original Message-----

**Comment by alanhumphrey** [comment]
Never mind my previous email.  I don’t know what’s going on when I run syncdb, but if I run loaddata the fixtures get loaded into the database correctly.

Again, thanks for your patience.  I’m looking forward to playing with the app.
-   Alan

-----Original Message-----
