### ISSUE TITLE
Incorrect Javascript Param Names

### ISSUE THREAD

**Issue by ahinz** [OpenTreeMap/otm-legacy#10]
https://github.com/azavea/OpenTreeMap/blob/c0ba7e8faf4e1fdd48754ac9828a1761b5743c30/static/js/map_init.js
https://github.com/azavea/OpenTreeMap/blob/c0ba7e8faf4e1fdd48754ac9828a1761b5743c30/static/js/page_init.js

Javascript should use mapCenterLon/mapCenterLat instead of the non-existent variable map_center_lon

**Comment by ahinz** [comment]
This issue is only on the 1.2 dev branch

**Comment by jwalgran** [comment]
Fixed in the v1.2 branch 9b8a72c7
