### ISSUE TITLE
dependencies not reflected in readme

### ISSUE THREAD

**Issue by alanhumphrey** [OpenTreeMap/otm-legacy#12]
there is a dependency on python-django-threadedcomments that is not reflected in the readme.  The "Required libraries from aptitude" should be updated.

there is a dependency on geopy_extensions that is not reflected in the readme.  I'm not able to figure out where to get it.

**Comment by jeffschuler** [comment]
Yes to having to install threadedcomments.

Also had to `pip install south`

As far as geopy_extensions, I followed @jlivni's lead (01731c45735977936ff619cb41f682a9cddddf0b) and commented-out the two references to it.

**Comment by alanhumphrey** [comment]
a new dependency: omgeo

```
sudo pip install python-omgeo
```

**Comment by ahinz** [comment]
Closed by d83474c077aaba
