### ISSUE TITLE
Docs should indicate need to import CHOICES

### ISSUE THREAD

**Issue by jeffschuler** [OpenTreeMap/otm-legacy#13]
README and/or [First Installation doc](https://github.com/azavea/OpenTreeMap/wiki/First-Installation) should indicate that it's necessary to import CHOICES data into settings.

Otherwise, `manage.py syncdb` fails:

```
File "/var/www/opentreemap/treemap/models.py", line 542, in Plot
type = models.CharField(max_length=256, null=True, blank=True, choices=settings.CHOICES["plot_types"])
AttributeError: 'Settings' object has no attribute 'CHOICES'
```

Maybe instruct folks to:
1. `cp treemaps/choices.py choices_LOCATION.py`
2. And add `from choices_LOCATION import *` to the settings.py file...

**Comment by alsaihn** [comment]
A note about the choices.py file has been added to the First Installation wiki page. Thanks!
