### ISSUE TITLE
Added measurements are not saving

### ISSUE THREAD

**Issue by ghost** [OpenTreeMap/otm-legacy#17]
I do not know anything about code but I am a user of the site and hope someone could help fix this. Whenever I go to edit a tree and enter in a diameter measurement, the value is not saved. After reloading the tree details it still informs me that the Diameter is missing. 

Thanks for any input

**Comment by dboyer** [comment]
Thanks for letting us know that you are having difficulty with editing the diameter measurement. Which OpenTreeMap site are you using? Are you using a website version of the software or one of the mobile apps?

**Comment by ghost** [comment]
I am using PhillyTeeMap. I have tried entering the measurement both on the website version and mobile app version, neither are working. I also tried it in 3 different browsers; chrome, safari and firefox. 

Thank you for the help!

**Comment by dboyer** [comment]
Thanks for the feedback. We'll look into it. I was able to successfully edit a tree diameter on PhillyTreeMap in Firefox so I'll dig around a bit and see if I can replicate the problem.

**Comment by ghost** [comment]
Huh, maybe the problem is on my end. I noticed in chrome that it was blocking content because it said it was insecure. The content being blocked was the tree map actually loading. So I allowed chrome to load it anyways. Then tried entering my data but that's when the trouble of saving came up. I'm not sure if that is a part of the problem or not.

**Comment by dboyer** [comment]
I was able to replicate the issue, and we'll look into it. Thanks for letting us know. In the mean time, I think you can actually edit the diameter if you try editing it a second time on the same tree. The first edit doesn't save, but I've found that when I go an edit the diameter again that it usually saves. Hopefully this will let you add diameter information until we can fix the issue.

**Comment by ghost** [comment]
Ok, I am glad you were able to replicate the problem. Thank you for looking into it. I tried entering it in twice and it did not seem to work for me but I will keep trying. 

On another note, I am a heavy user of the phillytreemap website because of a school project I am working on. If I have more issues or suggestions is this the best place to post them? Or should I move my discussion over to the Google Group created for OpenTreeMap?

**Comment by dboyer** [comment]
If you run into bugs or have specific feature suggestions, feel free to add them as issues here. We're happy to have comments on the Google Group too, but logging bugs here is a good idea. Thanks!

**Comment by ghost** [comment]
I talked with one of the computer science professors at my college about this issue and we concluded that its probably a database problem. What we found was that certain trees that I was trying to edit were not saving while other ones were. So I added a new tree next to a nonworking tree and I was able to save data into the new tree. This just means I have to remap some trees (hopefully not too many) and delete the old ones. I have noticed there is not a delete option on the phillytreemap website but in iOS app there is. Is it possible to add this option to the website?

**Comment by jwalgran** [comment]
@shortshorter The ability to delete trees is generally reserved for administrative users and the delete feature is available on both the website and the iOS application. All PhillyTreeMap users have the ability to delete the trees that they, themselves, have added, but may not delete any other trees.

In my testing of the iOS application I was able to delete trees which I had added, but I was not able to delete other user's trees. If you find that you are able to delete trees in the iOS application that you did not personally add to the map, please let us know as we would like to open another issue to get that problem resolved.

Thanks for your help.

**Comment by dboyer** [comment]
After testing in multiple browsers, we could not replicate this bug around added measurements not saving. Closing.
