### ISSUE TITLE
Consider adding a version number to JSON/HStore fields

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-legacy#174]

**Comment by maurizi** [comment]
@jwalgran Do you remember the reasoning behind this? Can we close this issue? Is it something you'd still like to do?

**Comment by jwalgran** [comment]
As long as JSON/HStore migrations are applied to to the fields transactionally (which is the case in Django migrations), there is no real need to keep a version number. We will never have a mix of old and new JSON/HStore schemas in different rows of the same table.
