### ISSUE TITLE
Geography import data sample schema

### ISSUE THREAD

**Issue by rukku** [OpenTreeMap/otm-legacy#2]
Hi, I'm having a bit of trouble with importing the geographies to PostgreSQL based on the descriptions. Could you please post sample schemas? Thanks :)

**Comment by alsaihn** [comment]
Hi. If you take a look at the Neighborhood and ZipCode classes (models.py around lines 124 and 151) the fields there are basically the schema. Each row for a neighborhood needs to have the following fields: name, region_id (which I don't think is used yet), city, county, state and geometry(the actual polygon).  ZipCodes only need the numeric zipcode and geometry columns. If you edit your shapefile to have those columns, you can use the PostgreSQL utility shp2pgsql. Here's some info on that utility: http://postgis.refractions.net/docs/ch04.html#shp2pgsql_usage

**Comment by rukku** [comment]
Oh... my bad. Forgot to check models.py. Python newbie here. Thanks :)
