### ISSUE TITLE
Allow users to delete trees and planting sites they have added to the map

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-legacy#22]
A user should always be able to delete the trees and planting sites that they have added to the map, regardless of reputation.

**Comment by ahinz** [comment]
This works correctly in the iPhone app but not in the web versions?

**Comment by jwalgran** [comment]
Yes. I believe it is just an overloaded template issue. The UI for deleting is missing.

**Comment by andrewbt** [comment]
Has this been resolved? Maybe in the new default template? Just checking.

**Comment by andrewbt** [comment]
also #17

**Comment by ghost** [comment]
This is has not been resolved as I still do not see a delete feature on the website.

**Comment by steventlamb** [comment]
Fixed (in ptm implementation).
