### ISSUE TITLE
dependencies not reflected in readme

### ISSUE THREAD

**Issue by alanhumphrey** [OpenTreeMap/otm-legacy#27]
(accidentally closed issue 12, creating new issue to capture the problems)

there is a dependency on python-django-threadedcomments that is not reflected in the readme. The "Required libraries from aptitude" should be updated.

there is a dependency on geopy_extensions that is not reflected in the readme. I'm not able to figure out where to get it.

(geopy_extensions can apparently be commented out with no ill effect.

additional dependencies:

Also had to `pip install south`

```
sudo pip install python-omgeo
```

**Comment by andrewbt** [comment]
I was wondering if that closure was by accident. The comment thread from #12 and link to @jlivni's commit are useful, so I re-opened #12 and will close this one instead.
