### ISSUE TITLE
ImportError: No module named UrbanForestMap.treemap

### ISSUE THREAD

**Issue by iman95** [OpenTreeMap/otm-legacy#3]
1. I run : python manage.py syncdb
   everything seemed to be fine, some tables and indexes were created, but there is a "No fixtures found." message. Is that normal?
2. Then I run : python manage.py update_aggregates
   error message appeared "ImportError: No module named UrbanForestMap.treemap"

Is there any missing step?

**Comment by ahinz** [comment]
1. No fixtures found is the correct message. Currently we don't have any fixtures to seed your database with.
2. This was indeed a bug. We just fixed it (https://github.com/azavea/OpenTreeMap/commit/04b8f2185105704872194a5f9e7c76c123b7c13a)

If you pull down from github you should be able to run the update_aggregates manage.py command.

Let me know if you have any more problems

**Comment by iman95** [comment]
I have update update_aggregates.py file,
the error disappeared, but anathor error message appear:
django.db.utils.DatabaseError: relation "treemap_tree" does not exist
LINE 1: ...llect("treemap_tree"."geometry") AS "geoagg" FROM "treemap_t...

It seems that table "treemap_tree" is not generated from previous command (python manage.py syncdb)

How to generate treemap_tree table?
