### ISSUE TITLE
Problem in installing OpenTreeMap

### ISSUE THREAD

**Issue by iman95** [OpenTreeMap/otm-legacy#4]
I have a problem when installing OpenTreeMap.

Run: "python manage.py syncdb" --> success, tables and index created.

When running "python manage.py update_aggregates"
Error message appear:
django.db.utils.DatabaseError: relation "treemap_tree" does not exist
LINE 1: ...llect("treemap_tree"."geometry") AS "geoagg" FROM "treemap_t...

It seems that table "treemap_tree" is not created from previous command (python manage.py syncdb)

Where is the script to create "treemap_tree" table?

**Comment by ahinz** [comment]
Hey Iman95 - syncdb should be creating the treemap_tree table and in some test runs we did not have any problems with that here. I'm going to close this issue, since I don't think it is a code issue.

If you are still having problems try sending an email to the user group (http://groups.google.com/group/opentreemap-user) and see if we can help you over there.

**Comment by iman95** [comment]
Hi Adam,
sorry for late response.

I still could not create the table after running "python manage.py syncdb" as seen on command below:

user@ubuntu:~/OpenTreeMap$ sudo python manage.py syncdb
Creating tables ...
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table auth_user_user_permissions
Creating table auth_user_groups
Creating table auth_user
Creating table auth_message
Creating table django_content_type
Creating table django_session
Creating table django_site
Creating table django_admin_log
Creating table django_comments
Creating table django_comment_flags
Creating table django_flatpage_sites
Creating table django_flatpage
Creating table registration_registrationprofile
Creating table django_reputation_reputation
Creating table django_reputation_reputationcontent
Creating table django_reputation_reputationaction
Creating table django_reputation_userreputationaction
Creating table django_reputation_permission
Creating table tagging_tag
Creating table tagging_taggeditem
Creating table treekey_species
Creating table treekey_speciesimage
Creating table treekey_specieslink
Creating table treekey_node_species
Creating table treekey_node
Creating table treekey_nodeimage

You just installed Django's auth system, which means you don't have any superusers defined.
Would you like to create one now? (yes/no): y
Please enter either "yes" or "no": yes
Username (Leave blank to use 'root'): 
E-mail address: iman95@yahoo.com
Password: 
Password (again): 
Superuser created successfully.
Installing custom SQL ...
Installing indexes ...
No fixtures found.

FYI i didn't install the following program:
- Map tile renderer - GeoServer(java) on tomcat is recommended (port 8081)
  And I just copied the following library to OpenTreeMap installation folder:
- django_reputation
- django_sorting
- pagination- sorl thumbnail

Is there any missing step? I can't find the script file associated with treemap_tree table?

Regards,
iman

**Comment by ahinz** [comment]
Hey iman - github issues are really not the place to discuss implementation issues. 

If you are still having problems try sending an email to the user group (http://groups.google.com/group/opentreemap-user) and see if we can help you over there.

Please try running: "python manage.py sql treemap" and posting the results over on the google group.

Thanks,
Adam

**Comment by iman95** [comment]
Halo Adam,
Here is the result:

user@ubuntu:~/OpenTreeMap$ sudo python manage.py sql treemap
[sudo] password for user: 
Traceback (most recent call last):
 File "manage.py", line 11, in <module>
 execute_manager(settings)
 File "/usr/lib/pymodules/python2.7/django/core/management/**init**.py", line 438, in execute_manager
 utility.execute()
 File "/usr/lib/pymodules/python2.7/django/core/management/**init**.py", line 379, in execute
 self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/usr/lib/pymodules/python2.7/django/core/management/base.py", line 191, in run_from_argv
 self.execute(_args, *_options.**dict**)
 File "/usr/lib/pymodules/python2.7/django/core/management/base.py", line 220, in execute
 output = self.handle(_args, *_options)
 File "/usr/lib/pymodules/python2.7/django/core/management/base.py", line 281, in handle
 app_list = [models.get_app(app_label) for app_label in app_labels]
 File "/usr/lib/pymodules/python2.7/django/db/models/loading.py", line 134, in get_app
 mod = self.load_app(app_name, False)
 File "/usr/lib/pymodules/python2.7/django/db/models/loading.py", line 78, in load_app
 models = import_module('.models', app_name)
 File "/usr/lib/pymodules/python2.7/django/utils/importlib.py", line 35, in import_module
 **import**(name)
 File "/home/user/OpenTreeMap/treemap/models.py", line 162, in <module>
 class Factoid(models.Model):
 File "/home/user/OpenTreeMap/treemap/models.py", line 163, in Factoid
 category = models.CharField(max_length=255, choices=Choices().get_field_choices('factoid'))
 File "/home/user/OpenTreeMap/treemap/models.py", line 98, in get_field_choices
 for c in Choices.objects.filter(field__exact=fieldName):
AttributeError: 'NoneType' object has no attribute 'objects'

Regards,
Iman

**Comment by ahinz** [comment]
If you are still having problems try sending an email to the user group (http://groups.google.com/group/opentreemap-user) and see if we can help you over there.

90% of the time this problem occurs because dependencies (particularly django_reputation) are not properly installed.

**Comment by iman95** [comment]
Hi Adam,
thank you for your help.
I have sent an email to the group.

Regards,
Iman
