### ISSUE TITLE
Data exports working incorrectly when exporting results of advanced search filter 

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-legacy#76]
After conducting a search using an advanced search filter, exporting those search results causes the following problems:

Shapefile - empty zip file
CSV - only species spreadsheet is available, no plots or trees files
KML - Trees and plots kml files available but opening in Google Earth causes the error - 

Open of file "c:\temp\wze49f\trees.kml" failed: Parse error at line 3, column 12: mismatched tag

Exports work properly when exporting all trees or the results of species or location searches.

**Comment by ahinz** [comment]
Closed by #103
