### ISSUE TITLE
it would be very helpful to include some automated process to install requirements 

### ISSUE THREAD

**Issue by pdaire** [OpenTreeMap/otm-legacy#77]
I only know about the requirements.txt file that allow a "pip install"

**Comment by Guerillero** [comment]
Yes please. I am running into issues like this

**Comment by ahinz** [comment]
We've added the requirements.txt file. Also, check out the wiki article https://github.com/azavea/OpenTreeMap/wiki/Install-Process-on-Ubuntu-12.04
