### ISSUE TITLE
Amazon AMI available?

### ISSUE THREAD

**Issue by maning** [OpenTreeMap/otm-legacy#8]
Is there an Amzon AMI I can use to create my own OpenTreeMap instance?

**Comment by ahinz** [comment]
Hi @maning. This question was recently asked on the mailing list and the answer is, unfortunately, no:

"We do not have a pre-built AMI for EC2, but the San Francisco Urban Forest Map instance runs in EC2, so I'm confident it will work.  However, the OpenTreeMap platform is under pretty active development and keeping an AMI current is a fair amount of work, so it's not something we are currently investing in."

https://groups.google.com/forum/?fromgroups#!topic/opentreemap-user/QUt9l4keyVU
