### ISSUE TITLE
treemap_species table has incorrect native_status field definition

### ISSUE THREAD

**Issue by andrewbt** [OpenTreeMap/otm-legacy#82]
This potentially affects the speciesimport.py importer as well as the table. From Bob Troester's post on mailing list:

"I noticed in the speciesimport.py code that there are boolean tests for 5 fields in the treemap_species table, but when I looked at the table definition itself\* one of those fields, native_status, wasn't marked boolean but char varying(255). If I had populated that field and tried to import it with speciesimport.py the program would have failed with an error message. 

When the treemap_species table was created with syncdb(?), it had been initialized with three records, and that native_status field displays "False" or "True" in normal text - clearly not what is wanted. (Also, the native status in these default records for the Maple and Cherry species is given as False - and that must be false!)."

**Comment by ahinz** [comment]
This is a major pain for the v1.x series. There were a bunch of fields that were initially mis-typed. Unfortunately that was before we got our hands on it and there are already instances running with this data.

It was decided that it was too dangerous to change that datatype of the field.

More discussion here: https://github.com/azavea/OpenTreeMap/pull/103

In the v2.x series datatypes are not dumb
