### ISSUE TITLE
Malformed import statement in treemap/management/commands scripts?

### ISSUE THREAD

**Issue by andrewbt** [OpenTreeMap/otm-legacy#83]
From Bob Troester on mailing list:

"I had followed the standard  Install-Process-on-Ubuntu-12.04 instructions to the letter and had ended up with OTM in 

**/var/www/opentreemap**

as the instructions specify. 

But the treemap/management/commands, speciesimport.py, itree_import.py, ui_import.py, resave_trees.py, update_aggregates.py, and testimports.py all contain code to load

**from OpenTreeMap.treemap.models**

and failed to run until I renamed my OTM project directory using capital letters as shown. These commands seem to be the only code in the entire project with that characteristic. 

**Part 2**

Also, build_exports.py has a "load" from UrbanForestMap and I guess only works in San Francisco!"

**Comment by ahinz** [comment]
I think this was fixed by @kbornhorst in https://github.com/azavea/OpenTreeMap/pull/84
