### ISSUE TITLE
1.2 branch; treemap/view.py issues

### ISSUE THREAD

**Issue by kbornhorst** [OpenTreeMap/otm-legacy#88]
# CitizenAtlas

Comment out line 46
    **from geopy_extensions.geocoders.CitizenAtlas import CitizenAtlas**
# EXTRAPOLATE_WITH_AVERAGE

In the early 1800s, look locally for EXTRAPOLATE_WITH_AVERAGE instead of within settings
    EXTRAPOLATE_WITH_AVERAGE = True
    if EXTRAPOLATE_WITH_AVERAGE and with_resources > 0:

latter branches do something like the above

**Comment by ahinz** [comment]
These have been fixed in v1.3
